### ISSUE TITLE
Missing spark-traces-aws-cluster-2017-11-22?

### ISSUE THREAD

**Issue by marvsz** [nanites/In-Network-Hadoop-NDN-CacheSimulator#3]
Hi,

I am very interested in your project and tried running the runTests.sh script but the repository seems to be missing the spark-traces-aws-cluster-2017-11-22 directory which should be above the root directory of this project?
It would be very helpful to me if you could provide me with that directory and its contents or even with a small readme to run your application?

Best

**Comment by eric135** [comment]
Thanks for your interest in our project. The directory in question contains traces from our evaluations (as described in our paper "On the Power of In-Network Caching in the Hadoop Distributed File System," which will appear in ACM ICN 2019 later this month). These traces are taken from evaluation clusters run on AWS on the date in question and then separated by application and phase.

Also, runTests.sh is intended to be run from within the "build" directory generated by running make. It is not stored in that directory because "make clean" deletes that directory. Moreover, it is a fair bit out of date, with out-of-date arguments to the simulator, hardcoded paths, and excluding some functional policies (namely 2Q). Instead of improving this script (which was intended to automate evaluations), I would highly recommend instead running the simulator directly (the correct arguments can be found by running CacheSim without any arguments).

If you would like, I could add a README describing the trace format and how to run the simulator, as well as adding the traces we used in our evaluations.

**Comment by marvsz** [comment]
Hi,
Thank you for your reply. I would appreciate it very much if you could provide a readme, thank you very much!

Best

**Comment by eric135** [comment]
The README is in the repository now. I also included some traces in the `traces` directory and some topologies in the `topologies` folder.
